/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel Cardona (https://sketchfab.com/DanielCardonaArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-color-852a3f56078240a69162b93919d5b1af
Title: Computer : Color
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const GamingPC=(props)=> {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL+'/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[-0.057, -0.017, -0.015]}
        rotation={[-1.561, 0.032, 0]}>
        <group name="a304cd30608b4ba9b63c1ff116ff27a2fbx" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="NewLayer0_Single_Sided_Material_0"
            castShadow
            receiveShadow
            geometry={nodes.NewLayer0_Single_Sided_Material_0.geometry}
            material={materials.Single_Sided_Material}
          />
          <mesh
            name="NewLayer0_Single_Sided_Material_0_1"
            castShadow
            receiveShadow
            geometry={nodes.NewLayer0_Single_Sided_Material_0_1.geometry}
            material={materials.Single_Sided_Material}
          />
          <mesh
            name="NewLayer0_Single_Sided_Material_0_2"
            castShadow
            receiveShadow
            geometry={nodes.NewLayer0_Single_Sided_Material_0_2.geometry}
            material={materials.Single_Sided_Material}
          />
          <mesh
            name="NewLayer0_Single_Sided_Material_0_3"
            castShadow
            receiveShadow
            geometry={nodes.NewLayer0_Single_Sided_Material_0_3.geometry}
            material={materials.Single_Sided_Material}
          />
          <mesh
            name="NewLayer0_Double_Sided_Material_0"
            castShadow
            receiveShadow
            geometry={nodes.NewLayer0_Double_Sided_Material_0.geometry}
            material={materials.Double_Sided_Material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL+'/computer__color.glb');
export default GamingPC;
